LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_CPP_FEATURES += exceptions

LOCAL_C_INCLUDES := $(LOCAL_PATH)/stk-4.4.3/include
LOCAL_MODULE    := synth
LOCAL_SRC_FILES := synth.cpp 


LOCAL_SRC_FILES +=  stk-4.4.3/src/ADSR.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Asymp.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/BandedWG.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/BeeThree.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/BiQuad.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Blit.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/BlitSaw.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/BlitSquare.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/BlowBotl.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/BlowHole.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Bowed.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Brass.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Chorus.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Clarinet.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/DelayA.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Delay.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/DelayL.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/Drummer.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Echo.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Envelope.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/FileLoop.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/FileRead.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/FileWrite.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/FileWvIn.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/FileWvOut.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Fir.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Flute.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/FM.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/FMVoices.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/FormSwep.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/Granulate.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/HevyMetl.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Iir.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/InetWvIn.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/InetWvOut.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/JCRev.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/LentPitShift.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/Mandolin.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Mesh2D.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Messager.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/MidiFileIn.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/ModalBar.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Modal.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Modulate.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/Moog.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/Mutex.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Noise.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/NRev.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/OnePole.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/OneZero.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/PercFlut.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Phonemes.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/PitShift.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Plucked.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/PoleZero.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/PRCRev.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Resonate.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/Rhodey.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/RtAudio.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/RtMidi.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/RtWvIn.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/RtWvOut.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Sampler.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Saxofony.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Shakers.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/Simple.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/SineWave.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/SingWave.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Sitar.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Skini.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/Socket.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Sphere.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/StifKarp.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Stk.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/TapDelay.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/TcpClient.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/TcpServer.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/Thread.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/TubeBell.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Twang.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/TwoPole.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/TwoZero.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/UdpSocket.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/Voicer.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/VoicForm.cpp
LOCAL_SRC_FILES +=  stk-4.4.3/src/Whistle.cpp
#LOCAL_SRC_FILES +=  stk-4.4.3/src/Wurley.cpp


include $(BUILD_SHARED_LIBRARY)
